// <auto-generated />
using System;
using AuditIQ.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuditIQ.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AuditIQDbContext))]
    [Migration("20260910045723_AddAuditLog")]
    partial class AddAuditLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuditIQ.Domain.Entities.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Action")
                        .HasColumnType("int");

                    b.Property<string>("Changes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("LegacySourceId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset>("TimestampUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LegacySourceId");

                    b.HasIndex("TimestampUtc");

                    b.HasIndex("EntityName", "EntityId");

                    b.ToTable("AuditLogEntries", (string)null);
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.CalibrationAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnswerValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("CalibrationRatingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CauseCode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("LegacySourceId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal?>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("ScorecardQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LegacySourceId");

                    b.HasIndex("ScorecardQuestionId");

                    b.HasIndex("CalibrationRatingId", "ScorecardQuestionId")
                        .IsUnique();

                    b.ToTable("CalibrationAnswers", (string)null);
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.CalibrationList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LegacySourceId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("VisibilityScope")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("LegacySourceId");

                    b.ToTable("CalibrationLists", (string)null);
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.CalibrationListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CalibrationListId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LegacySourceId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("LegacySourceId");

                    b.HasIndex("CalibrationListId", "EvaluationId")
                        .IsUnique();

                    b.ToTable("CalibrationListItems", (string)null);
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.CalibrationRating", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CalibrationListItemId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EvaluatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LegacySourceId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal?>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluatorId");

                    b.HasIndex("LegacySourceId");

                    b.HasIndex("CalibrationListItemId", "EvaluatorId")
                        .IsUnique();

                    b.ToTable("CalibrationRatings", (string)null);
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.CauseCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LegacySourceId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("LegacySourceId");

                    b.ToTable("CauseCodes", (string)null);
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.CommentLibraryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LegacySourceId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("Id");

                    b.HasIndex("LegacySourceId");

                    b.ToTable("CommentLibraryItems", (string)null);
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.Evaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisputeReason")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("EvaluatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EvaluatorNotes")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int?>("EventDurationSeconds")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("EventOccurredAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid?>("EventSubTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("EventTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LegacySourceId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal?>("LegacyTotalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<string>("Reference")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ResolutionNotes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("ScorecardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<decimal?>("TotalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("EvaluatorId");

                    b.HasIndex("EventOccurredAt");

                    b.HasIndex("EventSubTypeId");

                    b.HasIndex("EventTypeId");

                    b.HasIndex("LegacySourceId");

                    b.HasIndex("ScorecardId");

                    b.HasIndex("Status");

                    b.ToTable("Evaluations", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("EvaluationsHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.EvaluationAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AnswerValue")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("CauseCode")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LegacySourceId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal?>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<Guid>("ScorecardQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("LegacySourceId");

                    b.HasIndex("ScorecardQuestionId");

                    b.HasIndex("EvaluationId", "ScorecardQuestionId")
                        .IsUnique();

                    b.ToTable("EvaluationAnswers", (string)null);
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.EvaluationAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EvaluationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LegacySourceId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("LegacySourceId");

                    b.ToTable("EvaluationAttachments", (string)null);
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.EventSubType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventTypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LegacySourceId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LegacySourceId");

                    b.HasIndex("EventTypeId", "Name")
                        .IsUnique();

                    b.ToTable("EventSubTypes", (string)null);
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.EventType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LegacySourceId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LegacySourceId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EventTypes", (string)null);
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LegacySourceId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LegacySourceId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Groups", (string)null);
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.Kudos", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LegacySourceId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("FromUserId");

                    b.HasIndex("LegacySourceId");

                    b.HasIndex("ToUserId");

                    b.ToTable("Kudos", (string)null);
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.QuestionAnswerOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsFailAll")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFailSection")
                        .HasColumnType("bit");

                    b.Property<bool>("IsNotApplicable")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("LegacySourceId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("ScorecardQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<decimal>("Value")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("LegacySourceId");

                    b.HasIndex("ScorecardQuestionId");

                    b.ToTable("QuestionAnswerOptions", (string)null);
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.Scorecard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCurrentVersion")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLocked")
                        .HasColumnType("bit");

                    b.Property<string>("LegacySourceId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Location")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<decimal?>("MaxScore")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<Guid>("ScorecardGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ScorecardType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<decimal?>("TargetPercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("LegacySourceId");

                    b.HasIndex("ScorecardGroupId")
                        .IsUnique()
                        .HasDatabaseName("IX_Scorecards_CurrentVersion")
                        .HasFilter("[IsCurrentVersion] = 1");

                    b.HasIndex("ScorecardGroupId", "Version")
                        .IsUnique();

                    b.ToTable("Scorecards", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("ScorecardsHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.ScorecardCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LegacySourceId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LegacySourceId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ScorecardCategories", (string)null);
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.ScorecardOrgGroup", b =>
                {
                    b.Property<Guid>("ScorecardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ScorecardId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("ScorecardOrgGroups", (string)null);
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.ScorecardQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsFailLogic")
                        .HasColumnType("bit");

                    b.Property<string>("LegacySourceId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("ScorecardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SectionName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Weight")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LegacySourceId");

                    b.HasIndex("ScorecardId");

                    b.ToTable("ScorecardQuestions", (string)null);
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.ScorecardTipSheet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegacySourceId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid>("ScorecardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LegacySourceId");

                    b.HasIndex("ScorecardId");

                    b.ToTable("ScorecardTipSheets", (string)null);
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.ScreenPermission", b =>
                {
                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("ScreenKey")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("bit");

                    b.HasKey("Role", "ScreenKey");

                    b.ToTable("ScreenPermissions", (string)null);
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.Survey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LegacySourceId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.HasKey("Id");

                    b.HasIndex("LegacySourceId");

                    b.ToTable("Surveys", (string)null);
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.SurveyResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<Guid?>("EvaluationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LegacySourceId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int?>("Score")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EvaluationId");

                    b.HasIndex("LegacySourceId");

                    b.HasIndex("SurveyId");

                    b.ToTable("SurveyResponses", (string)null);
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LegacySourceId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("LegacySourceId");

                    b.HasIndex("GroupId", "Name")
                        .IsUnique();

                    b.ToTable("Teams", (string)null);
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EmploymentType")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LegacySourceId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("PeriodEnd")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodEnd");

                    b.Property<DateTime>("PeriodStart")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("datetime2")
                        .HasColumnName("PeriodStart");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("SsoSubjectId")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<Guid?>("SupervisorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("LegacySourceId");

                    b.HasIndex("SsoSubjectId")
                        .IsUnique();

                    b.HasIndex("SupervisorId");

                    b.ToTable("Users", (string)null);

                    b.ToTable(tb => tb.IsTemporal(ttb =>
                            {
                                ttb.UseHistoryTable("UsersHistory");
                                ttb
                                    .HasPeriodStart("PeriodStart")
                                    .HasColumnName("PeriodStart");
                                ttb
                                    .HasPeriodEnd("PeriodEnd")
                                    .HasColumnName("PeriodEnd");
                            }));
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.UserGroup", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("UserGroups", (string)null);
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.UserTeam", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "TeamId");

                    b.HasIndex("TeamId");

                    b.ToTable("UserTeams", (string)null);
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.CalibrationAnswer", b =>
                {
                    b.HasOne("AuditIQ.Domain.Entities.CalibrationRating", "CalibrationRating")
                        .WithMany("Answers")
                        .HasForeignKey("CalibrationRatingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditIQ.Domain.Entities.ScorecardQuestion", "ScorecardQuestion")
                        .WithMany()
                        .HasForeignKey("ScorecardQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CalibrationRating");

                    b.Navigation("ScorecardQuestion");
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.CalibrationList", b =>
                {
                    b.HasOne("AuditIQ.Domain.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.CalibrationListItem", b =>
                {
                    b.HasOne("AuditIQ.Domain.Entities.CalibrationList", "CalibrationList")
                        .WithMany("Items")
                        .HasForeignKey("CalibrationListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditIQ.Domain.Entities.Evaluation", "Evaluation")
                        .WithMany()
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CalibrationList");

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.CalibrationRating", b =>
                {
                    b.HasOne("AuditIQ.Domain.Entities.CalibrationListItem", "CalibrationListItem")
                        .WithMany("Ratings")
                        .HasForeignKey("CalibrationListItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditIQ.Domain.Entities.User", "Evaluator")
                        .WithMany()
                        .HasForeignKey("EvaluatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CalibrationListItem");

                    b.Navigation("Evaluator");
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.Evaluation", b =>
                {
                    b.HasOne("AuditIQ.Domain.Entities.User", "Agent")
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AuditIQ.Domain.Entities.User", "Evaluator")
                        .WithMany()
                        .HasForeignKey("EvaluatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AuditIQ.Domain.Entities.EventSubType", "EventSubType")
                        .WithMany()
                        .HasForeignKey("EventSubTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AuditIQ.Domain.Entities.EventType", "EventType")
                        .WithMany()
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AuditIQ.Domain.Entities.Scorecard", "Scorecard")
                        .WithMany()
                        .HasForeignKey("ScorecardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Evaluator");

                    b.Navigation("EventSubType");

                    b.Navigation("EventType");

                    b.Navigation("Scorecard");
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.EvaluationAnswer", b =>
                {
                    b.HasOne("AuditIQ.Domain.Entities.Evaluation", "Evaluation")
                        .WithMany("Answers")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditIQ.Domain.Entities.ScorecardQuestion", "ScorecardQuestion")
                        .WithMany()
                        .HasForeignKey("ScorecardQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Evaluation");

                    b.Navigation("ScorecardQuestion");
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.EvaluationAttachment", b =>
                {
                    b.HasOne("AuditIQ.Domain.Entities.Evaluation", "Evaluation")
                        .WithMany("Attachments")
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.EventSubType", b =>
                {
                    b.HasOne("AuditIQ.Domain.Entities.EventType", "EventType")
                        .WithMany("SubTypes")
                        .HasForeignKey("EventTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EventType");
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.Kudos", b =>
                {
                    b.HasOne("AuditIQ.Domain.Entities.User", "FromUser")
                        .WithMany()
                        .HasForeignKey("FromUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AuditIQ.Domain.Entities.User", "ToUser")
                        .WithMany()
                        .HasForeignKey("ToUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("FromUser");

                    b.Navigation("ToUser");
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.QuestionAnswerOption", b =>
                {
                    b.HasOne("AuditIQ.Domain.Entities.ScorecardQuestion", "ScorecardQuestion")
                        .WithMany("AnswerOptions")
                        .HasForeignKey("ScorecardQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScorecardQuestion");
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.Scorecard", b =>
                {
                    b.HasOne("AuditIQ.Domain.Entities.ScorecardCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.ScorecardOrgGroup", b =>
                {
                    b.HasOne("AuditIQ.Domain.Entities.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditIQ.Domain.Entities.Scorecard", "Scorecard")
                        .WithMany("OrgGroups")
                        .HasForeignKey("ScorecardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("Scorecard");
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.ScorecardQuestion", b =>
                {
                    b.HasOne("AuditIQ.Domain.Entities.Scorecard", "Scorecard")
                        .WithMany("Questions")
                        .HasForeignKey("ScorecardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scorecard");
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.ScorecardTipSheet", b =>
                {
                    b.HasOne("AuditIQ.Domain.Entities.Scorecard", "Scorecard")
                        .WithMany("TipSheets")
                        .HasForeignKey("ScorecardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scorecard");
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.SurveyResponse", b =>
                {
                    b.HasOne("AuditIQ.Domain.Entities.Evaluation", "Evaluation")
                        .WithMany()
                        .HasForeignKey("EvaluationId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("AuditIQ.Domain.Entities.Survey", "Survey")
                        .WithMany("Responses")
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evaluation");

                    b.Navigation("Survey");
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.Team", b =>
                {
                    b.HasOne("AuditIQ.Domain.Entities.Group", "Group")
                        .WithMany("Teams")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.User", b =>
                {
                    b.HasOne("AuditIQ.Domain.Entities.User", "Supervisor")
                        .WithMany("DirectReports")
                        .HasForeignKey("SupervisorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Supervisor");
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.UserGroup", b =>
                {
                    b.HasOne("AuditIQ.Domain.Entities.Group", "Group")
                        .WithMany("UserGroups")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditIQ.Domain.Entities.User", "User")
                        .WithMany("UserGroups")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.UserTeam", b =>
                {
                    b.HasOne("AuditIQ.Domain.Entities.Team", "Team")
                        .WithMany("UserTeams")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AuditIQ.Domain.Entities.User", "User")
                        .WithMany("UserTeams")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.CalibrationList", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.CalibrationListItem", b =>
                {
                    b.Navigation("Ratings");
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.CalibrationRating", b =>
                {
                    b.Navigation("Answers");
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.Evaluation", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.EventType", b =>
                {
                    b.Navigation("SubTypes");
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.Group", b =>
                {
                    b.Navigation("Teams");

                    b.Navigation("UserGroups");
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.Scorecard", b =>
                {
                    b.Navigation("OrgGroups");

                    b.Navigation("Questions");

                    b.Navigation("TipSheets");
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.ScorecardQuestion", b =>
                {
                    b.Navigation("AnswerOptions");
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.Survey", b =>
                {
                    b.Navigation("Responses");
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.Team", b =>
                {
                    b.Navigation("UserTeams");
                });

            modelBuilder.Entity("AuditIQ.Domain.Entities.User", b =>
                {
                    b.Navigation("DirectReports");

                    b.Navigation("UserGroups");

                    b.Navigation("UserTeams");
                });
#pragma warning restore 612, 618
        }
    }
}
