apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "helpers.name" . }}
  namespace: {{ include "helpers.namespace" . }}
  annotations:
    iam.gke.io/gcp-service-account: {{ include "helpers.gsa" . }}
